version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: et_user
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=supersecurejwtkey
      - DB_URL=postgres://et_user:securepass@db:5432/expense_tracker
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pgdata:
